spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://192.168.88.247:3306/mybatis?useUnicode=true&characterEncoding=utf8&useSSL=false
        name:
        username: root
        password: 123456
        hikari:
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
