spring:
    application:
        name: cloud-grpc-server
    cloud:
        zookeeper:
            connectString: localhost:2181,localhost:2182,localhost:2183
            discovery:
                instanceHost: 127.0.0.1
                instancePort: ${server.port}
server:
    port: 8886
grpc:
    server:
        port: 9999
#spring.cloud.zookeeper.connectString=192.168.1.100:2181
#spring.cloud.zookeeper.discovery.instanceHost=192.168.2.10
#spring.cloud.zookeeper.discovery.instancePort=${server.port}
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

